dist: focal
language: cpp
compiler:
- clang++

addons:
  apt:
    update: true
    packages:
    - nasm
    - grub2
    - xorriso
    - cmake
    - mtools
    - clang-10

script:
  - ln -s /usr/bin/clang-10 /usr/local/bin/clang
  - ln -s /usr/bin/clang-10 /usr/local/bin/clang++
  - mkdir build && cd build
  - cmake .. -G "Unix Makefiles"
  - make
  - make test