dist: focal
language: cpp
compiler:
  - clang


matrix:
  include:
    - compiler: clang
      addons:
        apt:
          update: true
          packages:
            - clang-10
            - nasm
            - grub2
            - xorriso
            - cmake
            - mtools
      - env: CXX=clang++-10 CC=clang-10 ASM=nasm
      

script:
  - mkdir build && cd build
  - cmake .. -G "Unix Makefiles"
  - make
  - make test