dist: focal
language:
  - cpp
compiler:
  - clang


before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install -y nasm grub2 xorriso mtools cmake
  - sudo apt-get install -y clang-10
  - export CC=/usr/bin/clang-10
  - export CXX=/usr/bin/clang++-10

script:
  - which clang
  - which clang-10
  - which ls
  - sudo ln -sf /usr/bin/clang-10 /usr/bin/clang
  - sudo ln -sf /usr/bin/clang++-10 /usr/bin/clang++
  - which clang
  - which clang-10
  - mkdir build && cd build
  - cmake .. -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10
  - make
  - make test