dist: focal
language:
  - cpp
compiler:
  - clang


before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install -y nasm grub2 xorriso mtools cmake
  - sudo apt-get install -y clang-10

script:
  - sudo ln -sf /usr/bin/clang-10 /usr/bin/clang
  - sudo ln -sf /usr/bin/clang++-10 /usr/bin/clang++
  - export PATH="/usr/bin:$PATH"
  - mkdir build && cd build
  - cmake .. -G "Unix Makefiles"
  - make
  - make test