dist: focal
sudo: required
language:
  - cpp
compiler:
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - nasm
      - grub2
      - xorriso
      - cmake
      - mtools
      - clang-10
script:
  - sudo ln -s /usr/bin/clang-10 /usr/local/bin/clang
  - sudo ln -s /usr/bin/clang++-10 /usr/local/bin/clang++
  - export CC=/usr/bin/clang-10
  - export CXX=/usr/bin/clang++-10
  - gcc -v && g++ -v && cmake --version
  - mkdir build && cd build
  - cmake .. -G "Unix Makefiles"
  - make
  - make test