dist: focal
language: cpp
compiler:
  - clang


matrix:
  include:
    - compiler: clang
      addons:
        apt:
          update: true
          packages:
            - clang-10
            - nasm
            - grub2
            - xorriso
            - cmake
            - mtools
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
before_install:
  - eval "${MATRIX_EVAL}"
      

script:
  - mkdir build && cd build
  - cmake .. -G "Unix Makefiles"
  - make
  - make test