dist: focal
language: cpp
compiler:
- g++

addons:
  apt:
    update: true
    packages:
    - nasm
    - grub2
    - xorriso
    - cmake
    - mformat

script:
- mkdir build && cd build
- cmake ..
- make
- make test