language: cpp
compiler:
- g++

before_install:
- sudo apt-get update
- sudo apt-get install g++-multilib nasm python cmake grub2 xorriso

script:
- mkdir build && cd build
- cmake ..
- make
- make test